name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#python
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#example-adding-configurations
        include:
          - python-version: "3.10"
            requirements: "dev"
          - python-version: "3.10"
            requirements: "min"
          - python-version: "3.12"
            requirements: "max"
          - python-version: "3.12"
            requirements: "np1"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install ${{ matrix.requirements }} dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/${{ matrix.requirements }}.txt
    - name: Run tests
      run: |
        python -m unittest
